### ISSUE TITLE
No face is getting fetch from image url.

### ISSUE THREAD

**Issue by jaswantjatav** [moonjava2005/face-recognition-react-native#1]
Hello ,
Thanks for such repo for react-native, I have tried to integrate into react-native app but I can't see any array of fetched faces.

I used this method.
       detectFaces('https://github.com/justadudewhohacks/face-api.js/blob/master/examples/images/bbt4.jpg?raw=true').then(result => {
             console.log("image:",result);
         }, e => {
             console.log("error by jja:",e);
         }); 

I also tried to fetch a local image but no luck.

Does this lib includes all methods what provided by https://github.com/justadudewhohacks/face-recognition.js

Thanks
jaswant

**Comment by jaswantjatav** [comment]
HI any update.?

**Comment by moonjava2005** [comment]
Dear @jaswantjatav 
I will fix it today

**Comment by jaswantjatav** [comment]
I do really need your help,
You really created a good! lib, I would like to use that, but I can't use it.
Can you please tell me that, what methods you implemented for facerecognition into this library. 
I am excited to use this library for face.
Thanks
Jaswant

**Comment by moonjava2005** [comment]
> I do really need your help,
> You really created a good! lib, I would like to use that, but I can't use it.
> Can you please tell me that, what methods you implemented for facerecognition into this library.
> I am excited to use this library for face.
> Thanks
> Jaswant

I used Google SDK for face recognization. Please update, I've just fixed the bug for network image
