### ISSUE TITLE
Can't find  any method for Face Recognition.

### ISSUE THREAD

**Issue by jaswantjatav** [moonjava2005/face-recognition-react-native#2]
Hi,
Thanks for your support, image fetching is working fine now, all faces are being listed.

Now the main goal is to recognise the detected faces, that I can't understand that how I can achieve it. As you did not mention how to use face recognition ,you only mentioned that how to detect faces from a image. Kindly help me to explain how I can recognise face using your library. ?

Thanks
Jaswant

**Comment by jaswantjatav** [comment]
Hi,
Can you please confirm , if this repo provides face recognition methods.?


Thanks
Jaswant

**Comment by moonjava2005** [comment]
> Hi,
> Can you please confirm , if this repo provides face recognition methods.?
> 
> Thanks
> Jaswant

Please read the document and follow the Usage

**Comment by jaswantjatav** [comment]
Hi,
I read the document, but there only single method mentioned for face detection, there is no method mentioned for face recognition , I also checked lib files here only face detection methods implemented. 

Can you please show me where I can see the documentation for all available methods into this library. 

Thanks
